### ISSUE TITLE
FR: keep the file creation date the same as the input file

### ISSUE THREAD

**Issue by mesqueeb** [developer0hye/BatchedFFmpeg#3]
I have a bunch of home videos in `.avi` and `.mov` format I want to all convert to mp4.
However, trying a batch ffmpeg caused all the new `.mp4` files to have the file creation date of today.

Ideally I wanna keep the original file creation dates, because then I know in what year the videos were made.

Do you think it's feasible to add this?

**Comment by developer0hye** [comment]
Is it okay to write date in your video file as a metadata?

**Comment by mesqueeb** [comment]
@developer0hye thank you for your message. 
Yeah that would be ok as well, I plan to import them into photos app later and I think the photos app prioritises the metadata over the file creation date. 

You might need to introduce exiftool as a new dependency though? Sorry if the request is tricky 😅

**Comment by developer0hye** [comment]
@mesqueeb How about writing date in filename?

a.avi -> a_20121224.mp4 

Is it okay?

Do you want converted video files to be sorted by metadata?

Or do you just want to know the creation date?

**Comment by mesqueeb** [comment]
dear @developer0hye , happy new year! 🎉 

I have about 800 videos (avi and mov) in a folder and I want to:
1. convert them to .mp4
2. add them to the Apple Photos app

For 2. I need to make sure the videos will keep the correct "media create data" or "file create date" so that they show up correctly on the timeline.

Sadly, just adding the date to the filename will not be enough.

I used exiftool to scan all videos and log out the `MediaCreateDate` and `CreateDate`:
```fish
# fish shell
for i in *.*; exiftool "($i)" -MediaCreateDate -CreateDate; end
```
and it seems for all videos, both the `MediaCreateDate` and `CreateDate` are the same values:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/3253920/147842413-4d0069bc-b232-4553-a37e-6fc369ad93ea.png">


## My request for batchedFFMpeg

1. execute `ffmpeg` with default options on each file to create `mp4`
2. copy over the `MediaCreateDate` and `CreateDate` from the original file onto the new mp4 with exiftool

Do you think you could add this feature? : )

**Comment by developer0hye** [comment]
@mesqueeb 
Thanks for your detailed explanation!

I will try to implement this function. 

Could you give me example video files whose extension is `.avi` and `.mkv`?

**Comment by mesqueeb** [comment]
@developer0hye 

I have zipped 3 video files
- 2 `.mov` files and one `.avi`
- one of the `.mov` doesn't give proper preview on macOS, which is something I hope to resolve when converting to mp4 as well

I don't have `.mkv` ! Sorry

I chose the smallest videos I could find. : )

[Archive.zip](https://github.com/developer0hye/BatchedFFmpeg/files/7799247/Archive.zip)

thank you :)

**Comment by developer0hye** [comment]
@mesqueeb 

Hi Lucas! It's been a long time.

I implemented code for your issue but I didn't update the code of the repository because I am considering your case is common.

I tried to read modification data(=creation data) from input videos, and I write this date into .mp4 file as a meta data.

Run the below code! and please tell me the results.

I really really want it to be worked for your case!

```python
import os
from datetime import datetime

import sys
import pathlib

video_exts = ('webm', 'mkv', 'flv', 'vob', 'ogv', 'ogg', 'rrc', 
        'gifv', 'mng', 'mov', 'avi', 'qt', 'wmv', 'yuv', 
        'rm', 'asf', 'amv', 'mp4', 'm4p', 'm4v', 'mpg',
        'mp2', 'mpeg', 'mpe', 'mpv', 'm4v', 'svi', '3gp',
        '3g2', 'mxf', 'roq', 'nsv', 'flv', 'f4v', 'f4p',
        'f4a', 'f4b')

img_exts = ('png', 'jpg', 'jpeg', 'bmp')

media_exts = video_exts + img_exts

def read_files(path, exts):
    exts = tuple(exts)
    files = []
    for r, d, f in os.walk(path):
        for file in f:
            if not file.lower().endswith(exts):
                continue     
            files.append(os.path.join(r, file))
    return files

def get_output_file_type(file):
    file_type = ""
    if file.endswith(video_exts):
        file_type = "video"
    elif file.endswith(img_exts):
        file_type = "img"
    else:
        raise TypeError(f"{file} is unvalid as an output. Valid output list: {video_exts} or {img_exts}")
    return file_type

def get_modified_time(file):
    return datetime.fromtimestamp(os.path.getmtime(file)).strftime('%Y-%m-%d %H:%M:%S')

def main():
    argv = sys.argv[1:]
    
    assert "-i" in argv, "usage: batchedffmpeg * -i {folder or file} *"
    
    idx_input_option = [i for i, arg in enumerate(argv) if arg == "-i"]
    assert len(idx_input_option) == 1, "usage: "
    idx_input_option = idx_input_option[0]
    
    assert len(argv) - 1 != idx_input_option, "usage: batchedffmpeg * -i {folder or file} *"
    idx_input_file = idx_input_option + 1
    input_path = argv[idx_input_file]
    
    if os.path.isfile(input_path):
        os.system("ffmpeg " + ' '.join(argv))
    elif os.path.isdir(input_path):
        
        video_files = read_files(input_path, video_exts)
        
        idx_output_file = [i for i, arg in enumerate(argv[idx_input_option + 2:]) 
                           if "." in arg and arg.endswith(media_exts)]
        
        assert len(idx_output_file) != 0, "At least one output file must be specified"
        idx_output_file = idx_input_option + 2 + idx_output_file[0]

        output_file = pathlib.Path(argv[idx_output_file])
        output_file_dir = output_file.parent
        output_file_fullname = output_file.name # with extension
        
        output_file_type = get_output_file_type(str(output_file_fullname))
     
        for video_file in video_files:            
            # change input
            argv[idx_input_file] = '"' + video_file + '"' # for whitespace, unicode
            
            # change output
            input_file_name = pathlib.Path(video_file).stem # without extension

            if output_file_type == "video":
                argv[idx_output_file] = os.path.join(output_file_dir, input_file_name + "_" + output_file_fullname)
            elif output_file_type == "img":
                output_file_save_folder = os.path.join(output_file_dir, input_file_name)
                os.makedirs(output_file_save_folder, exist_ok=True)
                argv[idx_output_file] = os.path.join(output_file_save_folder, input_file_name + "_" + output_file_fullname)

            input_file_modified_date = get_modified_time(video_file)
            
            argv[idx_input_file] += f' -metadata creation_time="{input_file_modified_date}"'   
            argv[idx_output_file] = '"' + argv[idx_output_file] + '"' # for whitespace, unicode
            
            print("ffmpeg " + ' '.join(argv))
            os.system("ffmpeg " + ' '.join(argv))
    else:
        raise FileNotFoundError(input_path, " is unvalid as an input.")
     
if __name__ == "__main__":
    main()
```

**Comment by developer0hye** [comment]
Ah I forgot to teach you how to run the above code.

1. Save the above code in file(batchedmmpeg-for-lucas.py)
2. run `python batchedmmpeg-for-lucas.py -i {your_videos_path} out.mp4`

**Comment by mesqueeb** [comment]
@developer0hye thank you so much! I will try tomorrow. 

The input path, should it be a folder? And out.mp4? Is it only a single file? Or will it discard the word `out` and use original file names?

**Comment by developer0hye** [comment]
@mesqueeb 

Input path can be a folder or file.

All output videos name would be {input_video_name}_out.mp4

**Comment by developer0hye** [comment]
@mesqueeb 
How is it going? Did you test this code?

**Comment by mesqueeb** [comment]
@developer0hye i will test tonight!!!

**Comment by developer0hye** [comment]
@mesqueeb 
Luca! Did you check it?

**Comment by mesqueeb** [comment]
@developer0hye 
I had no luck running it 😅
getting this error: 
<img width="571" alt="image" src="https://user-images.githubusercontent.com/3253920/149238136-cff8a073-265f-4ed1-9e44-af55530da82b.png">

Sorry! I don't know Python enough to figure this out : P I'm mainly a web developer

**Comment by developer0hye** [comment]
@mesqueeb 

Did you copy `video_exts` variable correctly? It's strange. T.T 
Can you print out `file`?

Modify `get_output_file_type` function like the below:

```python
def get_output_file_type(file):
    file_type = ""
    if file.endswith(video_exts):
        file_type = "video"
    elif file.endswith(img_exts):
        file_type = "img"
    else:
        print(file)
        raise TypeError(f"{file} is unvalid as an output. Valid output list: {video_exts} or {img_exts}")
    return file_type
```

**Comment by developer0hye** [comment]
Can you upload your command on this issue by text?

**Comment by mesqueeb** [comment]
@developer0hye I was able to run the script with `python3 ~~~~` 😅 

I tried on my zip and it seems to have worked.
The only issue raised in the terminal was:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/3253920/149436925-86b15e73-898f-45c8-9169-7d9fa1dfd48b.png">

But doing exiftool on the result gives me:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/3253920/149436955-d27a33a9-bbbf-46c0-8b80-2da80caa87f0.png">

so I think it's fine...? : O not sure what that red error was though.

**Comment by mesqueeb** [comment]
Thanks so much for this btw! I will use it to clean up my videos I needed to import over the weekend. < 3

**Comment by developer0hye** [comment]
@mesqueeb 

Hmm actually I don't know about that error.

Yes! I hope it will work for you~

I am surprised with your detailed FR. I could learn how to request FR through your FR.

**Comment by mesqueeb** [comment]
@developer0hye I do believe that most people would want to keep their original creation dates on their videos, right? So I hope you can re-consider having this be the default behaviour of your cli : )

**Comment by developer0hye** [comment]
@mesqueeb 
Can this modification cause unexepected results under various ffmpeg commands?

**Comment by mesqueeb** [comment]
I have only tried with your provided py script and it worked great on a folder of about 800 videos of various formats. 

I haven't tried with different ffmpeg settings.
